"use client";

/**
 * Product workflow API for an organisation's pursuits.
 *
 * This module deliberately owns the consumer contract while the OpenAPI client
 * is regenerated by the API delivery.  Keeping this thin boundary means the
 * new workflow can ship independently of code generation and does not leak
 * untyped request logic into pages.
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiMutate, fetchWithAuth } from "@/lib/api-client";
import { useActiveOrganizationId } from "@/hooks/use-organization";

export const PURSUIT_STATUSES = [
  "identified",
  "qualifying",
  "go_no_go",
  "preparing",
  "submitted",
  "won",
  "lost",
  "withdrawn",
] as const;

export type PursuitStatus = (typeof PURSUIT_STATUSES)[number];
export type PursuitDecision = "pending" | "go" | "no_go";
export type PursuitOutcome = "pending" | "won" | "lost" | "cancelled";

export interface Pursuit {
  id: number;
  organization_id: number;
  licitacion_id: string;
  tender_title: string | null;
  tender_deadline: string | null;
  responsible_user_id: number | null;
  responsible_name: string | null;
  status: PursuitStatus;
  decision: PursuitDecision;
  decision_reason: string | null;
  offer_price_eur: number | null;
  outcome: PursuitOutcome;
  awarded_amount_eur: number | null;
  outcome_reason: string | null;
  identified_at: string;
  decision_at: string | null;
  submitted_at: string | null;
  closed_at: string | null;
  created_at: string;
  updated_at: string;
  version: number;
  events?: Array<{ id: number; event_type: string; created_at: string }>;
}

export interface PursuitList {
  items: Pursuit[];
  total: number;
}

export interface CreatePursuitInput {
  licitacion_id: string;
  organization_id?: number;
}

export interface UpdatePursuitInput {
  status?: PursuitStatus;
  responsible_user_id?: number | null;
  decision?: PursuitDecision;
  decision_reason?: string | null;
  offer_price_eur?: number | null;
  outcome?: PursuitOutcome;
  awarded_amount_eur?: number | null;
  outcome_reason?: string | null;
  expected_version?: number;
}

export interface PursuitMetrics {
  pursuits_identified: number;
  pursuits_submitted: number;
  pursuits_won: number;
  pursuits_lost: number;
  win_rate: number | null;
  awarded_amount_eur: number;
  median_decision_time_hours: number | null;
}

export const pursuitKeys = {
  all: ["pursuits"] as const,
  list: (filters: PursuitFilters) => ["pursuits", "list", filters] as const,
  detail: (id: string) => ["pursuits", "detail", id] as const,
  metrics: ["pursuits", "metrics"] as const,
};

export interface PursuitFilters {
  status?: PursuitStatus;
  responsible_user_id?: number;
}

function pursuitQuery(filters: PursuitFilters, organizationId: number | null): string {
  const params = new URLSearchParams();
  if (filters.status) params.set("status", filters.status);
  if (filters.responsible_user_id) params.set("responsible_user_id", String(filters.responsible_user_id));
  if (organizationId != null) params.set("organization_id", String(organizationId));
  const search = params.toString();
  return search ? `?${search}` : "";
}

/**
 * `organizationId === null` no significa "sin datos": el backend resuelve la
 * organización personal automáticamente cuando se omite el parámetro. Por eso
 * estas queries se ejecutan siempre, en vez de quedar deshabilitadas hasta que
 * exista un ID explícito seleccionado en el frontend.
 */
export function usePursuits(filters: PursuitFilters = {}) {
  const organizationId = useActiveOrganizationId();
  return useQuery({
    queryKey: [...pursuitKeys.list(filters), organizationId],
    queryFn: () =>
      fetchWithAuth<PursuitList>(`/api/v1/pursuits${pursuitQuery(filters, organizationId)}`),
    staleTime: 30_000,
  });
}

export function usePursuit(id: string | null) {
  const organizationId = useActiveOrganizationId();
  return useQuery({
    queryKey: [...pursuitKeys.detail(id ?? ""), organizationId],
    queryFn: () => {
      const params = new URLSearchParams();
      if (organizationId != null) params.set("organization_id", String(organizationId));
      const query = params.toString();
      return fetchWithAuth<Pursuit>(
        `/api/v1/pursuits/${encodeURIComponent(id!)}${query ? `?${query}` : ""}`,
      );
    },
    enabled: Boolean(id),
  });
}

function invalidatePursuits(queryClient: ReturnType<typeof useQueryClient>) {
  return Promise.all([
    queryClient.invalidateQueries({ queryKey: pursuitKeys.all }),
    queryClient.invalidateQueries({ queryKey: pursuitKeys.metrics }),
    queryClient.invalidateQueries({ queryKey: ["organizations"] }),
  ]);
}

export function useCreatePursuit() {
  const queryClient = useQueryClient();
  const organizationId = useActiveOrganizationId();
  return useMutation({
    mutationFn: (input: CreatePursuitInput) =>
      apiMutate<Pursuit>("POST", "/api/v1/pursuits", {
        ...input,
        organization_id: input.organization_id ?? organizationId ?? undefined,
      }),
    onSuccess: () => invalidatePursuits(queryClient),
  });
}

export function useUpdatePursuit(id: string | number) {
  const queryClient = useQueryClient();
  const pursuitId = String(id);
  const organizationId = useActiveOrganizationId();
  return useMutation({
    mutationFn: (input: UpdatePursuitInput) => {
      const params = new URLSearchParams();
      if (organizationId != null) params.set("organization_id", String(organizationId));
      const query = params.toString();
      return apiMutate<Pursuit>(
        "PATCH",
        `/api/v1/pursuits/${encodeURIComponent(pursuitId)}${query ? `?${query}` : ""}`,
        input,
      );
    },
    onSuccess: (pursuit) => {
      queryClient.setQueryData(pursuitKeys.detail(pursuitId), pursuit);
      return invalidatePursuits(queryClient);
    },
  });
}

export function usePursuitMetrics() {
  const organizationId = useActiveOrganizationId();
  return useQuery({
    queryKey: [...pursuitKeys.metrics, organizationId],
    queryFn: () => {
      const params = new URLSearchParams();
      if (organizationId != null) params.set("organization_id", String(organizationId));
      const query = params.toString();
      return fetchWithAuth<PursuitMetrics>(`/api/v1/pursuits/metrics${query ? `?${query}` : ""}`);
    },
    staleTime: 60_000,
  });
}
