"""Keywords por tecnología para filtrar licitaciones del sector público.

Consumidores: ``scraper.filters``, ``scheduler.concept_drift``.
"""

from __future__ import annotations

# Palabras clave para filtrar licitaciones SAP
SAP_KEYWORDS: list[str] = [
    # Plataforma principal
    "sap",
    "s/4hana",
    "s4hana",
    "s/4 hana",
    "hana",
    "abap",
    "fiori",
    # Módulos funcionales
    "sap erp",
    "sap ecc",
    "sap basis",
    "sap mm",
    "sap fi",
    "sap fi/co",
    "sap co",
    "sap sd",
    "sap hcm",
    "sap hr",
    "sap pi",
    "sap po",
    "sap pm",
    "sap ps",
    "sap qm",
    "sap wm",
    "sap ewm",
    "sap tm",
    "sap srm",
    "sap crm",
    "sap ssm",
    "sap bi",
    "sap bo",
    "sap bw",
    "sap bpc",
    "sap grc",
    "sap mdg",
    "sap mdm",
    "sap isu",
    "sap is-u",
    "sap re-fx",
    "sap refx",
    "sap re/fx",
    "sap apo",
    "sap scm",
    "sap ibp",
    "sap slm",
    "sap clm",
    "sap ariba",
    "sap fieldglass",
    "sap concur",
    "sap analytics cloud",
    "sac sap",
    # Suite cloud
    "successfactors",
    "ariba",
    "concur",
    "fieldglass",
    "sap cx",
    "sap customer experience",
    # Infraestructura / tecnología
    "netweaver",
    "bw/4hana",
    "bw4hana",
    "sap solution manager",
    "solman",
    "businessobjects",
    "business objects",
    "crystal reports",
    "sap oss",
    "sap early watch",
    "sap lumira",
    "sap build",
    "sap integration suite",
    "sap btp",
    "business technology platform",
    "sap cloud platform",
    # Términos genéricos asociados
    "implantación sap",
    "migración sap",
    "mantenimiento sap",
    "soporte sap",
    "consultoría sap",
    "formación sap",
    "licencias sap",
    "upgrade sap",
    "actualización sap",
]

# Keywords por tecnología (multi-vendor).
# El scraper filtra licitaciones que coincidan con al menos una tecnología.
TECHNOLOGY_KEYWORDS: dict[str, list[str]] = {
    "SAP": SAP_KEYWORDS,
    "SALESFORCE": [
        "salesforce",
        "sales cloud",
        "service cloud",
        "marketing cloud",
        "commerce cloud",
        "experience cloud",
        "community cloud",
        "salesforce cpq",
        "salesforce crm",
        "pardot",
        "mulesoft",
        "tableau crm",
        "einstein analytics",
        "salesforce einstein",
        "heroku",
        "apex salesforce",
        "visualforce",
        "lightning",
        "salesforce platform",
        "force.com",
        "data cloud salesforce",
        "implantación salesforce",
        "migración salesforce",
        "mantenimiento salesforce",
        "soporte salesforce",
        "consultoría salesforce",
        "licencias salesforce",
    ],
    "ORACLE": [
        "oracle",
        "oracle erp",
        "oracle cloud",
        "oracle fusion",
        "oracle ebs",
        "e-business suite",
        "oracle hcm",
        "oracle financials",
        "peoplesoft",
        "jd edwards",
        "oracle database",
        "oracle db",
        "oracle weblogic",
        "oracle forms",
        "oracle apex",
        "oracle bi",
        "oracle analytics",
        "oracle integration cloud",
        "oracle soa",
        "primavera oracle",
        "siebel",
        "oracle netsuite",
        "netsuite",
        "pl/sql",
        "plsql",
        "implantación oracle",
        "migración oracle",
        "mantenimiento oracle",
        "soporte oracle",
        "consultoría oracle",
        "licencias oracle",
    ],
    "MICROSOFT": [
        "microsoft dynamics",
        "dynamics 365",
        "dynamics crm",
        "dynamics nav",
        "dynamics ax",
        "dynamics bc",
        "business central",
        "navision",
        "axapta",
        "power platform",
        "power bi",
        "power apps",
        "power automate",
        "microsoft azure",
        "azure devops",
        "sharepoint",
        "microsoft 365",
        "office 365",
        "microsoft teams",
        "sql server",
        "azure sql",
        ".net",
        "dotnet",
        "implantación dynamics",
        "migración dynamics",
        "mantenimiento dynamics",
        "soporte dynamics",
        "consultoría dynamics",
        "licencias dynamics",
        "licencias microsoft",
    ],
    "SERVICENOW": [
        "servicenow",
        "service now",
        "servicenow itsm",
        "servicenow itom",
        "servicenow hrsd",
        "servicenow csm",
        "implantación servicenow",
        "soporte servicenow",
        "licencias servicenow",
    ],
    "WORKDAY": [
        "workday",
        "workday hcm",
        "workday financials",
        "workday adaptive",
        "workday prism",
        "implantación workday",
        "soporte workday",
        "licencias workday",
    ],
    "IBM": [
        "ibm maximo",
        "ibm cognos",
        "ibm websphere",
        "ibm db2",
        "ibm cloud",
        "ibm watson",
        "ibm filenet",
        "ibm bpm",
        "lotus notes",
        "ibm as/400",
        "ibm iseries",
        "rpg ibm",
    ],
    "OPENTEXT": [
        "opentext",
        "open text",
        "documentum",
        "content server",
        "opentext ecm",
        "opentext extended ecm",
    ],
    "UNIT4": [
        "unit4",
        "unit 4",
        "unit4 erp",
        "unit4 financials",
        "agresso",
    ],
    "META4": [
        "meta4",
        "meta 4",
        "meta4 peoplenet",
        "peoplenet",
        "cezanne hr",
    ],
    "SOPRA": [
        "sopra",
        "sopra steria",
        "sap sopra",
    ],
    "SAGE": [
        "sage erp",
        "sage x3",
        "sage 200",
        "sage despachos",
        "sage murano",
        "sage 50",
    ],
    "INFOR": [
        "infor erp",
        "infor ln",
        "infor m3",
        "infor cloudsuite",
        "infor os",
        "baan",
    ],
}

# Lista canónica de etiquetas de tecnología (orden estable por inserción del dict).
# Consumida por ``scraper.tech_classifier`` para construir el matriz de labels
# y por la persistencia de scores en ``licitacion_tecnologia_score``.
TECH_LABELS: list[str] = list(TECHNOLOGY_KEYWORDS.keys())
