"""Keywords por tecnología para filtrar licitaciones del sector público.

Consumidores: ``scraper.filters``, ``scheduler.concept_drift``.

Dos tipos de etiqueta (2026-09-14, plan de arquitectura v2, «no salir de TI»)
-----------------------------------------------------------------------------
* **Fabricante** (``SAP``, ``SALESFORCE``, …): la taxonomía histórica. Cada
  lista nombra productos y módulos de un vendor concreto.
* **Categoría** (``ERP``, ``CRM``, ``CLOUD_INFRA``, ``CIBERSEGURIDAD``,
  ``DATOS_IA``, ``DESARROLLO``, ``GIS``, ``SANIDAD_DIGITAL``,
  ``ADMIN_ELECTRONICA``): qué se compra, sin decir de quién. Ensanchan la
  taxonomía **dentro** de TI: un integrador vende «un ERP» o «un SOC» tanto
  como vende SAP.

Las dos conviven en el mismo dict porque todo lo que consume el diccionario
—filtro, clasificador multi-etiqueta, señal de pliegos, analítica— itera sus
claves sin distinguirlas; :data:`TECH_LABEL_TIPO` es donde se distingue cuando
hace falta (UI, documentación).

Idiomas cooficiales
-------------------
La PSCP (Catalunya) publica en catalán, Euskadi en euskera y Galicia en
gallego. Un vocabulario solo en castellano explicaba parte del 0,46 % de
positivos de PSCP: «desenvolupament de programari» no casa con «desarrollo de
software». Por eso cada categoría lleva, además del castellano, las formas en
catalán, euskera y gallego **cuando difieren** (el gallego coincide a menudo
con el castellano, y entonces no se repite). Los fabricantes no lo necesitan:
«SAP» se escribe igual en los cuatro idiomas.

Criterio de precisión
---------------------
Se prefieren términos de varias palabras a palabras sueltas: «datos»,
«software» o «seguridad» a secas casan con todo, así que solo entran dentro
de sintagmas («analítica de datos», «desarrollo de software», «auditoría de
seguridad»). Los acrónimos cortos (``erp``, ``gis``, ``siem``) sí entran
porque el filtro compila con límites de palabra (véase
``services.tecnologias_diccionario.patrones``): «gis» no casa dentro de
«registro».
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from typing import Literal

# Palabras clave para filtrar licitaciones SAP
SAP_KEYWORDS: list[str] = [
    # Plataforma principal
    "sap",
    "s/4hana",
    "s4hana",
    "s/4 hana",
    "hana",
    "abap",
    "fiori",
    # Módulos funcionales
    "sap erp",
    "sap ecc",
    "sap basis",
    "sap mm",
    "sap fi",
    "sap fi/co",
    "sap co",
    "sap sd",
    "sap hcm",
    "sap hr",
    "sap pi",
    "sap po",
    "sap pm",
    "sap ps",
    "sap qm",
    "sap wm",
    "sap ewm",
    "sap tm",
    "sap srm",
    "sap crm",
    "sap ssm",
    "sap bi",
    "sap bo",
    "sap bw",
    "sap bpc",
    "sap grc",
    "sap mdg",
    "sap mdm",
    "sap isu",
    "sap is-u",
    "sap re-fx",
    "sap refx",
    "sap re/fx",
    "sap apo",
    "sap scm",
    "sap ibp",
    "sap slm",
    "sap clm",
    "sap ariba",
    "sap fieldglass",
    "sap concur",
    "sap analytics cloud",
    "sac sap",
    # Suite cloud
    "successfactors",
    "ariba",
    "concur",
    "fieldglass",
    "sap cx",
    "sap customer experience",
    # Infraestructura / tecnología
    "netweaver",
    "bw/4hana",
    "bw4hana",
    "sap solution manager",
    "solman",
    "businessobjects",
    "business objects",
    "crystal reports",
    "sap oss",
    "sap early watch",
    "sap lumira",
    "sap build",
    "sap integration suite",
    "sap btp",
    "business technology platform",
    "sap cloud platform",
    # Términos genéricos asociados
    "implantación sap",
    "migración sap",
    "mantenimiento sap",
    "soporte sap",
    "consultoría sap",
    "formación sap",
    "licencias sap",
    "upgrade sap",
    "actualización sap",
]

# Keywords por tecnología (multi-vendor).
# El scraper filtra licitaciones que coincidan con al menos una tecnología.
# ── SEMILLA, no fuente de verdad (C5.6, D28, v126) ──────────────────────────
#
# Desde v126 el diccionario vigente vive en la tabla `tecnologias_keywords` y se
# edita desde `/ops` sin desplegar. Esto es la **semilla**: lo que se vuelca en
# la tabla cuando está vacía (`services.tecnologias_diccionario.
# sembrar_desde_semilla`) y el respaldo si la base de datos no responde — sin
# él, un fallo de lectura dejaría el filtro sin diccionario, y un filtro sin
# diccionario no descarta nada: mete el censo entero.
#
# Añadir aquí una keyword ya **no** basta para que entre en producción: hay que
# resembrar. Lo que sí sigue estando aquí es la revisión en código de qué
# términos son legítimos, que es lo que una tabla editable no da.
TECHNOLOGY_KEYWORDS: dict[str, list[str]] = {
    "SAP": SAP_KEYWORDS,
    "SALESFORCE": [
        "salesforce",
        "sales cloud",
        "service cloud",
        "marketing cloud",
        "commerce cloud",
        "experience cloud",
        "community cloud",
        "salesforce cpq",
        "salesforce crm",
        "pardot",
        "mulesoft",
        "tableau crm",
        "einstein analytics",
        "salesforce einstein",
        "heroku",
        "apex salesforce",
        "visualforce",
        "lightning",
        "salesforce platform",
        "force.com",
        "data cloud salesforce",
        "implantación salesforce",
        "migración salesforce",
        "mantenimiento salesforce",
        "soporte salesforce",
        "consultoría salesforce",
        "licencias salesforce",
    ],
    "ORACLE": [
        "oracle",
        "oracle erp",
        "oracle cloud",
        "oracle fusion",
        "oracle ebs",
        "e-business suite",
        "oracle hcm",
        "oracle financials",
        "peoplesoft",
        "jd edwards",
        "oracle database",
        "oracle db",
        "oracle weblogic",
        "oracle forms",
        "oracle apex",
        "oracle bi",
        "oracle analytics",
        "oracle integration cloud",
        "oracle soa",
        "primavera oracle",
        "siebel",
        "oracle netsuite",
        "netsuite",
        "pl/sql",
        "plsql",
        "implantación oracle",
        "migración oracle",
        "mantenimiento oracle",
        "soporte oracle",
        "consultoría oracle",
        "licencias oracle",
    ],
    "MICROSOFT": [
        "microsoft dynamics",
        "dynamics 365",
        "dynamics crm",
        "dynamics nav",
        "dynamics ax",
        "dynamics bc",
        "business central",
        "navision",
        "axapta",
        "power platform",
        "power bi",
        "power apps",
        "power automate",
        "microsoft azure",
        "azure devops",
        "sharepoint",
        "microsoft 365",
        "office 365",
        "microsoft teams",
        "sql server",
        "azure sql",
        ".net",
        "dotnet",
        "implantación dynamics",
        "migración dynamics",
        "mantenimiento dynamics",
        "soporte dynamics",
        "consultoría dynamics",
        "licencias dynamics",
        "licencias microsoft",
    ],
    "SERVICENOW": [
        "servicenow",
        "service now",
        "servicenow itsm",
        "servicenow itom",
        "servicenow hrsd",
        "servicenow csm",
        "implantación servicenow",
        "soporte servicenow",
        "licencias servicenow",
    ],
    "WORKDAY": [
        "workday",
        "workday hcm",
        "workday financials",
        "workday adaptive",
        "workday prism",
        "implantación workday",
        "soporte workday",
        "licencias workday",
    ],
    "IBM": [
        "ibm maximo",
        "ibm cognos",
        "ibm websphere",
        "ibm db2",
        "ibm cloud",
        "ibm watson",
        "ibm filenet",
        "ibm bpm",
        "lotus notes",
        "ibm as/400",
        "ibm iseries",
        "rpg ibm",
    ],
    "OPENTEXT": [
        "opentext",
        "open text",
        "documentum",
        "content server",
        "opentext ecm",
        "opentext extended ecm",
    ],
    "UNIT4": [
        "unit4",
        "unit 4",
        "unit4 erp",
        "unit4 financials",
        "agresso",
    ],
    "META4": [
        "meta4",
        "meta 4",
        "meta4 peoplenet",
        "peoplenet",
        "cezanne hr",
    ],
    "SOPRA": [
        "sopra",
        "sopra steria",
        "sap sopra",
        "sopra hr",
        "sopra hr software",
        "hr access",
        "sopra banking",
    ],
    "SAGE": [
        "sage erp",
        "sage x3",
        "sage 200",
        "sage despachos",
        "sage murano",
        "sage 50",
    ],
    "INFOR": [
        "infor erp",
        "infor ln",
        "infor m3",
        "infor cloudsuite",
        "infor os",
        "baan",
    ],
    # ── Categorías (2026-09-14) ─────────────────────────────────────────────
    # Van detrás de los fabricantes a propósito: ``TECH_LABELS`` conserva el
    # orden de inserción y los índices de los trece primeros no se mueven.
    "ERP": [
        # es
        "erp",
        "sistema erp",
        "solución erp",
        "planificación de recursos empresariales",
        "sistema de gestión integrado",
        "sistema integrado de gestión",
        "gestión económico-financiera",
        "sistema de gestión económico-financiera",
        "sistema de información económico-financiero",
        "sistema de gestión económica",
        "contabilidad presupuestaria",
        "sistema de gestión contable",
        "sistema contable",
        "sistema de gestión tributaria",
        "sistema de nóminas",
        "software de nóminas",
        "sistema de gestión de recursos humanos",
        "sistema de información de recursos humanos",
        # ca
        "planificació de recursos empresarials",
        "sistema de gestió integrat",
        "sistema integrat de gestió",
        "gestió econòmica i financera",
        "gestió economicofinancera",
        "sistema de gestió econòmica",
        "comptabilitat pressupostària",
        "sistema de gestió comptable",
        "sistema comptable",
        "sistema de gestió tributària",
        "sistema de nòmines",
        "programari de nòmines",
        "sistema de gestió de recursos humans",
        # eu
        "enpresa baliabideen plangintza",
        "kudeaketa sistema integratua",
        "kudeaketa ekonomiko-finantzarioa",
        "kudeaketa ekonomikoko sistema",
        "aurrekontu kontabilitatea",
        "kontabilitate sistema",
        "zerga kudeaketako sistema",
        "nominen sistema",
        "nominen softwarea",
        "giza baliabideen kudeaketa sistema",
        # gl
        "planificación de recursos empresariais",
        "sistema de xestión integrado",
        "sistema integrado de xestión",
        "xestión económico-financeira",
        "xestión económica e financeira",
        "sistema de xestión económica",
        "contabilidade orzamentaria",
        "sistema de xestión contable",
        "sistema de xestión tributaria",
        "sistema de xestión de recursos humanos",
    ],
    "CRM": [
        # es
        "crm",
        "sistema crm",
        "solución crm",
        "plataforma crm",
        "customer relationship management",
        "citizen relationship management",
        "gestión de relaciones con clientes",
        "gestión de la relación con el cliente",
        "gestión de relaciones con la ciudadanía",
        "plataforma de atención ciudadana",
        "sistema de atención ciudadana",
        "gestión de clientes",
        "plataforma de contact center",
        "solución de contact center",
        "software de contact center",
        "plataforma de centro de contacto",
        "automatización de marketing",
        "gestión de la experiencia de cliente",
        # ca
        "gestió de relacions amb clients",
        "gestió de la relació amb el client",
        "gestió de relacions amb la ciutadania",
        "plataforma d'atenció ciutadana",
        "sistema d'atenció ciutadana",
        "gestió de clients",
        "plataforma de centre de contacte",
        "automatització de màrqueting",
        "gestió de l'experiència de client",
        # eu
        "bezeroekiko harremanen kudeaketa",
        "herritarrekiko harremanen kudeaketa",
        "herritarren arretarako plataforma",
        "herritarren arretarako sistema",
        "bezeroen kudeaketa",
        "kontaktu zentroko plataforma",
        "marketin automatizazioa",
        "bezeroaren esperientziaren kudeaketa",
        # gl
        "xestión de relacións con clientes",
        "xestión da relación co cliente",
        "xestión de relacións coa cidadanía",
        "plataforma de atención cidadá",
        "sistema de atención cidadá",
        "xestión de clientes",
        "automatización de márketing",
        "xestión da experiencia de cliente",
    ],
    "CLOUD_INFRA": [
        # es
        "servicios en la nube",
        "servicios cloud",
        "nube pública",
        "nube privada",
        "nube híbrida",
        "computación en la nube",
        "cloud computing",
        "migración a la nube",
        "infraestructura como servicio",
        "iaas",
        "plataforma como servicio",
        "paas",
        "software como servicio",
        "saas",
        "kubernetes",
        "docker",
        "openshift",
        "orquestación de contenedores",
        "plataforma de contenedores",
        "virtualización",
        "vmware",
        "hiperconvergencia",
        "infraestructura hiperconvergente",
        "centro de datos",
        "centro de proceso de datos",
        "cpd",
        "datacenter",
        "data center",
        "hosting",
        "alojamiento web",
        "cabina de almacenamiento",
        "sistema de almacenamiento",
        "almacenamiento en la nube",
        "copias de seguridad",
        "copia de seguridad",
        "backup",
        "recuperación ante desastres",
        "disaster recovery",
        "suministro de servidores",
        "servidores virtuales",
        # ca
        "serveis al núvol",
        "serveis en el núvol",
        "serveis de núvol",
        "núvol públic",
        "núvol privat",
        "núvol híbrid",
        "computació al núvol",
        "migració al núvol",
        "infraestructura com a servei",
        "plataforma com a servei",
        "programari com a servei",
        "orquestració de contenidors",
        "plataforma de contenidors",
        "virtualització",
        "centre de dades",
        "centre de procés de dades",
        "allotjament web",
        "cabina d'emmagatzematge",
        "sistema d'emmagatzematge",
        "emmagatzematge al núvol",
        "còpies de seguretat",
        "còpia de seguretat",
        "recuperació davant desastres",
        "subministrament de servidors",
        "servidors virtuals",
        # eu
        "hodeiko zerbitzuak",
        "hodeiko zerbitzu",
        "hodei publikoa",
        "hodei pribatua",
        "hodei hibridoa",
        "hodeiko konputazioa",
        "hodeirako migrazioa",
        "azpiegitura zerbitzu gisa",
        "plataforma zerbitzu gisa",
        "softwarea zerbitzu gisa",
        "edukiontzien orkestrazioa",
        "edukiontzi plataforma",
        "birtualizazioa",
        "datu zentroa",
        "datuak prozesatzeko zentroa",
        "web ostatatzea",
        "biltegiratze kabina",
        "biltegiratze sistema",
        "hodeiko biltegiratzea",
        "segurtasun kopiak",
        "segurtasun kopia",
        "hondamendien aurreko berreskuratzea",
        "zerbitzarien hornidura",
        "zerbitzari birtualak",
        # gl
        "servizos na nube",
        "computación na nube",
        "migración á nube",
        "infraestrutura como servizo",
        "plataforma como servizo",
        "software como servizo",
        "orquestración de contedores",
        "plataforma de contedores",
        "aloxamento web",
        "cabina de almacenamento",
        "sistema de almacenamento",
        "almacenamento na nube",
        "copias de seguranza",
        "copia de seguranza",
        "subministración de servidores",
        "servidores virtuais",
    ],
    "CIBERSEGURIDAD": [
        # es
        "ciberseguridad",
        "seguridad informática",
        "seguridad de la información",
        "seguridad de los sistemas de información",
        "esquema nacional de seguridad",
        "adecuación al ens",
        "certificación ens",
        "cumplimiento del ens",
        "auditoría de seguridad",
        "auditoría de ciberseguridad",
        "análisis de vulnerabilidades",
        "gestión de vulnerabilidades",
        "test de intrusión",
        "pruebas de intrusión",
        "pentest",
        "pentesting",
        "hacking ético",
        "centro de operaciones de seguridad",
        "servicio de soc",
        "servicios de soc",
        "soc 24x7",
        "siem",
        "edr",
        "xdr",
        "mdr",
        "dlp",
        "waf",
        "firewall",
        "cortafuegos",
        "antivirus",
        "gestión de identidades",
        "gestión de identidades y accesos",
        "iam",
        "doble factor de autenticación",
        "autenticación multifactor",
        "cifrado de datos",
        "seguridad perimetral",
        "respuesta a incidentes",
        "ciberincidentes",
        "concienciación en ciberseguridad",
        "zero trust",
        "seguridad gestionada",
        "servicios de seguridad gestionada",
        # ca
        "ciberseguretat",
        "seguretat informàtica",
        "seguretat de la informació",
        "seguretat dels sistemes d'informació",
        "esquema nacional de seguretat",
        "adequació a l'ens",
        "auditoria de seguretat",
        "auditoria de ciberseguretat",
        "anàlisi de vulnerabilitats",
        "gestió de vulnerabilitats",
        "test d'intrusió",
        "proves d'intrusió",
        "centre d'operacions de seguretat",
        "servei de soc",
        "serveis de soc",
        "tallafocs",
        "gestió d'identitats",
        "gestió d'identitats i accessos",
        "autenticació multifactor",
        "xifratge de dades",
        "seguretat perimetral",
        "resposta a incidents",
        "conscienciació en ciberseguretat",
        "seguretat gestionada",
        # eu — el euskera declina el sustantivo («zibersegurtasun zerbitzuak»,
        # «zibersegurtasuna»): se listan la forma determinada y la raíz cuando
        # la raíz es la que aparece en los compuestos de los títulos.
        "zibersegurtasuna",
        "zibersegurtasun",
        "segurtasun informatikoa",
        "informazioaren segurtasuna",
        "informazio sistemen segurtasuna",
        "segurtasun eskema nazionala",
        "segurtasun auditoretza",
        "zibersegurtasun auditoretza",
        "ahultasunen analisia",
        "ahultasunen kudeaketa",
        "intrusio probak",
        "segurtasun eragiketen zentroa",
        "suebakia",
        "identitateen kudeaketa",
        "identitate eta sarbideen kudeaketa",
        "faktore anitzeko autentifikazioa",
        "datuen zifratzea",
        "segurtasun perimetrala",
        "gorabeheren erantzuna",
        "kudeatutako segurtasuna",
        # gl
        "ciberseguridade",
        "seguridade informática",
        "seguridade da información",
        "seguridade dos sistemas de información",
        "esquema nacional de seguridade",
        "adecuación ao ens",
        "auditoría de seguridade",
        "auditoría de ciberseguridade",
        "análise de vulnerabilidades",
        "xestión de vulnerabilidades",
        "probas de intrusión",
        "centro de operacións de seguridade",
        "servizo de soc",
        "servizos de soc",
        "xestión de identidades",
        "xestión de identidades e accesos",
        "seguridade perimetral",
        "resposta a incidentes",
        "concienciación en ciberseguridade",
        "seguridade xestionada",
    ],
    "DATOS_IA": [
        # es
        "business intelligence",
        "inteligencia de negocio",
        "cuadro de mando",
        "cuadros de mando",
        "analítica de datos",
        "analítica avanzada",
        "plataforma de datos",
        "data warehouse",
        "almacén de datos",
        "lago de datos",
        "data lake",
        "big data",
        "ciencia de datos",
        "gobierno del dato",
        "gobernanza del dato",
        "calidad del dato",
        "datos abiertos",
        "portal de datos abiertos",
        "inteligencia artificial",
        "ia generativa",
        "aprendizaje automático",
        "machine learning",
        "aprendizaje profundo",
        "deep learning",
        "procesamiento de lenguaje natural",
        "procesamiento del lenguaje natural",
        "modelos de lenguaje",
        "modelo predictivo",
        "modelos predictivos",
        "minería de datos",
        "visualización de datos",
        "asistente virtual",
        "chatbot",
        "visión artificial",
        # ca
        "intel·ligència de negoci",
        "quadre de comandament",
        "quadres de comandament",
        "analítica de dades",
        "analítica avançada",
        "plataforma de dades",
        "magatzem de dades",
        "llac de dades",
        "ciència de dades",
        "govern de la dada",
        "governança de la dada",
        "qualitat de la dada",
        "dades obertes",
        "portal de dades obertes",
        "intel·ligència artificial",
        "aprenentatge automàtic",
        "aprenentatge profund",
        "processament del llenguatge natural",
        "models de llenguatge",
        "model predictiu",
        "models predictius",
        "mineria de dades",
        "visualització de dades",
        "assistent virtual",
        "visió artificial",
        # eu
        "negozio adimena",
        "aginte koadroa",
        "aginte koadroak",
        "datuen analitika",
        "analitika aurreratua",
        "datu plataforma",
        "datu biltegia",
        "datu lakua",
        "datu zientzia",
        "datuen gobernantza",
        "datuaren gobernantza",
        "datuen kalitatea",
        "datu irekiak",
        "datu irekien ataria",
        "adimen artifiziala",
        "adimen artifizial",
        "ia sortzailea",
        "ikasketa automatikoa",
        "ikasketa sakona",
        "hizkuntza naturalaren prozesamendua",
        "hizkuntza ereduak",
        "eredu prediktiboa",
        "eredu prediktiboak",
        "datu meatzaritza",
        "datuen bistaratzea",
        "laguntzaile birtuala",
        "ikusmen artifiziala",
        # gl
        "intelixencia de negocio",
        "cadro de mando",
        "cadros de mando",
        "goberno do dato",
        "gobernanza do dato",
        "calidade do dato",
        "datos abertos",
        "portal de datos abertos",
        "intelixencia artificial",
        "aprendizaxe automática",
        "aprendizaxe profunda",
        "procesamento da linguaxe natural",
        "modelos de linguaxe",
        "modelo preditivo",
        "modelos preditivos",
    ],
    "DESARROLLO": [
        # es
        "desarrollo de software",
        "desarrollo de aplicaciones",
        "desarrollo a medida",
        "desarrollo de una aplicación",
        "desarrollo web",
        "diseño y desarrollo web",
        "desarrollo de la página web",
        "desarrollo del portal web",
        "desarrollo del sitio web",
        "desarrollo evolutivo",
        "mantenimiento evolutivo",
        "mantenimiento correctivo",
        "mantenimiento adaptativo",
        "mantenimiento de aplicaciones",
        "mantenimiento de software",
        "evolutivos y correctivos",
        "correctivos y evolutivos",
        "factoría de software",
        "fábrica de software",
        "servicios de desarrollo",
        "aplicación web",
        "aplicaciones web",
        "aplicación móvil",
        "aplicaciones móviles",
        "app móvil",
        "apps móviles",
        "api",
        "apis",
        "api rest",
        "microservicios",
        "arquitectura de microservicios",
        "devops",
        "integración continua",
        "desarrollo ágil",
        "metodología ágil",
        "pruebas de software",
        "testing de software",
        "aseguramiento de la calidad del software",
        # ca
        "desenvolupament de programari",
        "desenvolupament d'aplicacions",
        "desenvolupament a mida",
        "desenvolupament d'una aplicació",
        "desenvolupament web",
        "disseny i desenvolupament web",
        "desenvolupament de la pàgina web",
        "desenvolupament del portal web",
        "desenvolupament del lloc web",
        "desenvolupament evolutiu",
        "manteniment evolutiu",
        "manteniment correctiu",
        "manteniment adaptatiu",
        "manteniment d'aplicacions",
        "manteniment de programari",
        "evolutius i correctius",
        "correctius i evolutius",
        "factoria de programari",
        "fàbrica de programari",
        "serveis de desenvolupament",
        "aplicació web",
        "aplicacions web",
        "aplicació mòbil",
        "aplicacions mòbils",
        "app mòbil",
        "microserveis",
        "arquitectura de microserveis",
        "integració contínua",
        "desenvolupament àgil",
        "metodologia àgil",
        "proves de programari",
        # eu
        "software garapena",
        "software garapen",
        "softwarearen garapena",
        "aplikazioen garapena",
        "neurrira egindako garapena",
        "aplikazio baten garapena",
        "web garapena",
        "web diseinua eta garapena",
        "web orriaren garapena",
        "web atariaren garapena",
        "webgunearen garapena",
        "garapen ebolutiboa",
        "mantentze ebolutiboa",
        "mantentze zuzentzailea",
        "mantentze egokitzailea",
        "aplikazioen mantentzea",
        "softwarearen mantentzea",
        "software faktoria",
        "garapen zerbitzuak",
        "web aplikazioa",
        "web aplikazioak",
        "aplikazio mugikorra",
        "aplikazio mugikorrak",
        "mugikorretarako aplikazioa",
        "mikrozerbitzuak",
        "mikrozerbitzuen arkitektura",
        "integrazio jarraitua",
        "garapen arina",
        "metodologia arina",
        "software probak",
        # gl
        "desenvolvemento de software",
        "desenvolvemento de aplicacións",
        "desenvolvemento á medida",
        "desenvolvemento dunha aplicación",
        "desenvolvemento web",
        "deseño e desenvolvemento web",
        "desenvolvemento da páxina web",
        "desenvolvemento do portal web",
        "desenvolvemento do sitio web",
        "desenvolvemento evolutivo",
        "mantemento evolutivo",
        "mantemento correctivo",
        "mantemento adaptativo",
        "mantemento de aplicacións",
        "mantemento de software",
        "evolutivos e correctivos",
        "correctivos e evolutivos",
        "servizos de desenvolvemento",
        "aplicacións web",
        "aplicación móbil",
        "aplicacións móbiles",
        "app móbil",
        "microservizos",
        "arquitectura de microservizos",
        "desenvolvemento áxil",
        "metodoloxía áxil",
        "probas de software",
    ],
    "GIS": [
        # es
        "sistema de información geográfica",
        "sistemas de información geográfica",
        "gis",
        "webgis",
        "cartografía digital",
        "geoportal",
        "infraestructura de datos espaciales",
        "datos geoespaciales",
        "información geoespacial",
        "geolocalización",
        "georreferenciación",
        "visor cartográfico",
        "visor geográfico",
        "callejero digital",
        "arcgis",
        "qgis",
        "esri",
        "geoserver",
        # ca
        "sistema d'informació geogràfica",
        "sistemes d'informació geogràfica",
        "cartografia digital",
        "infraestructura de dades espacials",
        "dades geoespacials",
        "informació geoespacial",
        "geolocalització",
        "georeferenciació",
        "visor cartogràfic",
        "visor geogràfic",
        "carrerer digital",
        # eu
        "informazio geografikoko sistema",
        "informazio geografikoko sistemak",
        "kartografia digitala",
        "geoportala",
        "datu espazialen azpiegitura",
        "datu geoespazialak",
        "informazio geoespaziala",
        "geolokalizazioa",
        "georreferentziazioa",
        "ikustaile kartografikoa",
        "ikustaile geografikoa",
        # gl
        "sistema de información xeográfica",
        "sistemas de información xeográfica",
        "cartografía dixital",
        "infraestrutura de datos espaciais",
        "datos xeoespaciais",
        "información xeoespacial",
        "xeolocalización",
        "xeorreferenciación",
        "visor xeográfico",
        "rueiro dixital",
    ],
    "SANIDAD_DIGITAL": [
        # es
        "historia clínica electrónica",
        "historia clínica digital",
        "historia clínica informatizada",
        "historia de salud electrónica",
        "receta electrónica",
        "prescripción electrónica",
        "sistema de información hospitalaria",
        "sistema de información sanitaria",
        "sistema de información clínica",
        "sistema his",
        "his/pacs",
        "pacs",
        "ris/pacs",
        "ris-pacs",
        "imagen médica digital",
        "telemedicina",
        "teleconsulta",
        "telemonitorización",
        "salud digital",
        "sanidad digital",
        "carpeta de salud",
        "carpeta personal de salud",
        "sistema de cita previa",
        "gestión de pacientes",
        "sistema de gestión de pacientes",
        "interoperabilidad sanitaria",
        "estación clínica",
        "software sanitario",
        "software clínico",
        # ca
        "història clínica electrònica",
        "història clínica digital",
        "història clínica informatitzada",
        "història de salut electrònica",
        "recepta electrònica",
        "prescripció electrònica",
        "sistema d'informació hospitalària",
        "sistema d'informació sanitària",
        "sistema d'informació clínica",
        "imatge mèdica digital",
        "telemonitoratge",
        "salut digital",
        "sanitat digital",
        "carpeta de salut",
        "carpeta personal de salut",
        "sistema de cita prèvia",
        "gestió de pacients",
        "sistema de gestió de pacients",
        "interoperabilitat sanitària",
        "estació clínica",
        "programari sanitari",
        "programari clínic",
        # eu
        "historia kliniko elektronikoa",
        "historia kliniko digitala",
        "historia kliniko informatizatua",
        "osasun historia elektronikoa",
        "errezeta elektronikoa",
        "preskripzio elektronikoa",
        "ospitaleko informazio sistema",
        "osasun informazio sistema",
        "informazio klinikoko sistema",
        "irudi mediko digitala",
        "telemedikuntza",
        "telekontsulta",
        "telemonitorizazioa",
        "osasun digitala",
        "osasun karpeta",
        "osasun karpeta pertsonala",
        "aurretiko hitzordu sistema",
        "pazienteen kudeaketa",
        "pazienteen kudeaketa sistema",
        "osasun elkarreragingarritasuna",
        "estazio klinikoa",
        "osasun softwarea",
        "software klinikoa",
        # gl
        "historia clínica dixital",
        "historia de saúde electrónica",
        "receita electrónica",
        "prescrición electrónica",
        "imaxe médica dixital",
        "saúde dixital",
        "sanidade dixital",
        "carpeta de saúde",
        "carpeta persoal de saúde",
        "xestión de pacientes",
        "sistema de xestión de pacientes",
        "interoperabilidade sanitaria",
    ],
    "ADMIN_ELECTRONICA": [
        # es
        "administración electrónica",
        "e-administración",
        "administración digital",
        "sede electrónica",
        "tramitación electrónica",
        "tramitador electrónico",
        "registro electrónico",
        "firma electrónica",
        "firma digital",
        "certificado digital",
        "portafirmas",
        "portafirmas electrónico",
        "cl@ve",
        "interoperabilidad",
        "plataforma de interoperabilidad",
        "esquema nacional de interoperabilidad",
        "gestor de expedientes",
        "gestión de expedientes",
        "expediente electrónico",
        "gestor documental",
        "sistema de gestión documental",
        "archivo electrónico",
        "notificación electrónica",
        "notificaciones electrónicas",
        "carpeta ciudadana",
        "portal de transparencia",
        "portal del ciudadano",
        "licitación electrónica",
        "contratación electrónica",
        "factura electrónica",
        "facturación electrónica",
        # ca
        "administració electrònica",
        "administració digital",
        "seu electrònica",
        "tramitació electrònica",
        "tramitador electrònic",
        "registre electrònic",
        "signatura electrònica",
        "signatura digital",
        "certificat digital",
        "portasignatures",
        "interoperabilitat",
        "plataforma d'interoperabilitat",
        "esquema nacional d'interoperabilitat",
        "gestor d'expedients",
        "gestió d'expedients",
        "expedient electrònic",
        "sistema de gestió documental",
        "arxiu electrònic",
        "notificació electrònica",
        "notificacions electròniques",
        "carpeta ciutadana",
        "portal de transparència",
        "portal del ciutadà",
        "licitació electrònica",
        "contractació electrònica",
        "factura electrònica",
        "facturació electrònica",
        # eu
        "administrazio elektronikoa",
        "administrazio elektroniko",
        "administrazio digitala",
        "egoitza elektronikoa",
        "egoitza elektroniko",
        "izapidetze elektronikoa",
        "izapidetzaile elektronikoa",
        "erregistro elektronikoa",
        "sinadura elektronikoa",
        "sinadura digitala",
        "ziurtagiri digitala",
        "elkarreragingarritasuna",
        "elkarreragingarritasun plataforma",
        "elkarreragingarritasun eskema nazionala",
        "espedienteen kudeatzailea",
        "espedienteen kudeaketa",
        "espediente elektronikoa",
        "dokumentu kudeatzailea",
        "dokumentu kudeaketa sistema",
        "artxibo elektronikoa",
        "jakinarazpen elektronikoa",
        "jakinarazpen elektronikoak",
        "herritarren karpeta",
        "gardentasun ataria",
        "herritarraren ataria",
        "lizitazio elektronikoa",
        "kontratazio elektronikoa",
        "faktura elektronikoa",
        "fakturazio elektronikoa",
        # gl
        "administración dixital",
        "rexistro electrónico",
        "sinatura electrónica",
        "sinatura dixital",
        "certificado dixital",
        "portasinaturas",
        "interoperabilidade",
        "plataforma de interoperabilidade",
        "esquema nacional de interoperabilidade",
        "xestor de expedientes",
        "xestión de expedientes",
        "xestor documental",
        "sistema de xestión documental",
        "arquivo electrónico",
        "notificacións electrónicas",
        "carpeta cidadá",
        "portal do cidadán",
    ],
}

# Lista canónica de etiquetas de tecnología (orden estable por inserción del dict).
# Consumida por ``scraper.tech_classifier`` para construir el matriz de labels
# y por la persistencia de scores en ``licitacion_tecnologia_score``.
TECH_LABELS: list[str] = list(TECHNOLOGY_KEYWORDS.keys())

# Etiqueta legible de cada label, para la UI y la analítica. Es la única copia:
# ``services.classification.TECHNOLOGY_LABELS`` se deriva de aquí. Los textos de
# los fabricantes son los históricos y no se tocan — la analítica por tecnología
# agrupa por esta etiqueta (``services/analytics/tecnologias.py``) y cambiarlos
# partiría sus series igual que cambiar el diccionario.
TECH_CATEGORIAS: dict[str, str] = {
    "SAP": "SAP",
    "SALESFORCE": "Salesforce",
    "ORACLE": "Oracle",
    "MICROSOFT": "Microsoft Dynamics / Azure",
    "SERVICENOW": "ServiceNow",
    "WORKDAY": "Workday",
    "IBM": "IBM",
    "OPENTEXT": "OpenText",
    "UNIT4": "Unit4",
    "META4": "Meta4",
    "SOPRA": "Sopra",
    "SAGE": "Sage",
    "INFOR": "Infor",
    "ERP": "ERP (genérico)",
    "CRM": "CRM (genérico)",
    "CLOUD_INFRA": "Cloud e infraestructura",
    "CIBERSEGURIDAD": "Ciberseguridad",
    "DATOS_IA": "Datos e IA",
    "DESARROLLO": "Desarrollo de software",
    "GIS": "GIS y geoinformación",
    "SANIDAD_DIGITAL": "Sanidad digital",
    "ADMIN_ELECTRONICA": "Administración electrónica",
}

TipoLabel = Literal["fabricante", "categoria"]

# Qué es cada label. Un fabricante nombra a un vendor; una categoría nombra qué
# se compra sin decir de quién. Todo consumidor que necesite distinguirlas
# (UI, docs) pregunta aquí y no infiere nada del nombre.
TECH_LABEL_TIPO: dict[str, TipoLabel] = {
    "SAP": "fabricante",
    "SALESFORCE": "fabricante",
    "ORACLE": "fabricante",
    "MICROSOFT": "fabricante",
    "SERVICENOW": "fabricante",
    "WORKDAY": "fabricante",
    "IBM": "fabricante",
    "OPENTEXT": "fabricante",
    "UNIT4": "fabricante",
    "META4": "fabricante",
    "SOPRA": "fabricante",
    "SAGE": "fabricante",
    "INFOR": "fabricante",
    "ERP": "categoria",
    "CRM": "categoria",
    "CLOUD_INFRA": "categoria",
    "CIBERSEGURIDAD": "categoria",
    "DATOS_IA": "categoria",
    "DESARROLLO": "categoria",
    "GIS": "categoria",
    "SANIDAD_DIGITAL": "categoria",
    "ADMIN_ELECTRONICA": "categoria",
}

# Los tres mapas describen el mismo conjunto: un label sin etiqueta legible o
# sin tipo se rompería en la UI sin que ningún test de dominio lo viera. Se
# comprueba al importar (y no solo en tests) porque la semilla se vuelca en
# base de datos: un label huérfano aquí sería un label huérfano en producción.
if not (set(TECH_CATEGORIAS) == set(TECH_LABELS) == set(TECH_LABEL_TIPO)):
    raise ValueError(
        "TECHNOLOGY_KEYWORDS, TECH_CATEGORIAS y TECH_LABEL_TIPO deben declarar los mismos labels"
    )


# ── Límites de palabra para keywords que no empiezan (o acaban) en letra ────
#
# El patrón de siempre era ``\b(kw1|kw2|...)\b``, y con él **`.net` no puede
# casar nunca**: `\b` antes de un punto exige un carácter de palabra pegado, así
# que `\b\.net` sólo casa dentro de otra palabra (`asp.net`) y jamás en
# «plataforma .NET», que es como aparece en los pliegos. La keyword estaba en el
# diccionario desde su primera versión y no clasificaba nada; sólo se vio al
# escribir el test que compila cada término.
#
# Lo mismo le pasaría, del otro lado, a `c++` o a `c#`: `\b` después de `+` o
# `#` no casa detrás de un espacio.
#
# La regla es la misma de antes donde antes servía —letra pegada a letra— y se
# relaja sólo en el extremo donde el término no empieza ni acaba en carácter de
# palabra. El punto se excluye a la izquierda a propósito: así `.net` sigue sin
# casar dentro de `asp.net`, que es un producto distinto con su propia entrada.


def con_limites(keyword: str) -> str:
    """Fragmento de regex para ``keyword`` con el límite correcto a cada lado."""
    escapada = re.escape(keyword)
    izquierda = r"\b" if keyword[:1].isalnum() or keyword[:1] == "_" else r"(?<![\w.])"
    derecha = r"\b" if keyword[-1:].isalnum() or keyword[-1:] == "_" else r"(?!\w)"
    return f"{izquierda}{escapada}{derecha}"


def patron_de_keywords(keywords: Iterable[str], *, flags: int = re.IGNORECASE) -> re.Pattern[str]:
    """Regex que casa cualquiera de ``keywords``, cada una con sus límites.

    Fuente única del criterio: `services/tecnologias_diccionario.patrones`,
    `scraper/filters` y los tests compilan por aquí, de modo que arreglar un
    caso como `.net` lo arregla en los tres a la vez.
    """
    return re.compile("|".join(con_limites(k) for k in keywords if k), flags=flags)
